spring:
  servlet:
    multipart:
      max-file-size: 1024MB
      max-request-size: 1024MB
  datasource:
    type: com.alibaba.druid.pool.DruidDataSource
    driver-class-name: com.mysql.cj.jdbc.Driver
    url: jdbc:mysql://localhost:3306/common_basic
    username: root
    password: 123456


mybatis-plus:
  global-config:
    db-config:
      id-type: ASSIGN_ID
      logic-delete-field: isDelete
      logic-delete-value: 1
      logic-not-delete-value: 0
#  configuration:
#    log-impl: org.apache.ibatis.logging.stdout.StdOutImpl



# springdoc-openapi项目配置
springdoc:
  swagger-ui:
    path: /swagger-ui.html
    tags-sorter: alpha
    operations-sorter: alpha
  api-docs:
    path: /v3/api-docs
  group-configs:
    - group: 'default'
      paths-to-match: '/**'
      packages-to-scan: com.project.app
# knife4j的增强配置，不需要增强可以不配
knife4j:
  enable: true
  setting:
    language: zh_cn



server:
  port: 9001



self:
  conf:
    expires-time: 2D
    sec-key: 111111
    file-path: ${user.dir}/files/
    file-access-path: /attachment/**
    file-api: http://localhost:${server.port}/attachment/
    ignore-url:
      - /login
      - /swagger-ui/**
      - /doc.html
      - /webjars/**
      - /v3/api-docs/**
      - /attachment/**
      - /file/upload
      - /system/register